### ISSUE TITLE
Squares can contain more points than threshold

### ISSUE THREAD

**Issue by jesperdejby** [kpully/quadtree#1]
Hi!

Thanks a lot for this piece of code. Was really helpful to me. I found a minor error in the `recursive_subdivide()` function here:

` p = contains(node.x0+w_, node.y0+w_, w_, h_, node.points)`

That causes the split to occur incorrectly and therefore yield cases where the number of points in a square exceeds threshold. It should instead be:

 `p = contains(node.x0 + w_, node.y0 + h_, w_, h_, node.points)`

With this the algorithm runs as expected.

**Comment by kpully** [comment]
Thanks @jesperdejby - fixed this!
